### ISSUE TITLE
The game starts with a big delay.

### ISSUE THREAD

**Issue by angelsonly** [sungry/CS177#91] opened 2015-12-06 22:03 UTC
Is it the feature that cannot be fixed? As far as I understood....

**Comment by frostelicus** [comment] 2015-12-07 00:01
Looks like it just needs second to load up, might be a little longer as we add in more assets.

**Comment by angelsonly** [comment] 2015-12-08 21:42
On MAC

**Comment by designerzim** [comment] 2015-12-09 01:36
This seems to be a result of needing to click once to make the Unity player an active component, and /then/ they can click on start, which seems to start very fast after that.

We could possibly add some text to the HTML, or use a WebGL build (which is preview, but looks nice on a test build I just tried)

**Comment by EricSFChu** [comment] 2015-12-09 06:41
I believe the issue was caused by the button hit boxes being misaligned which causes the user to believe that the game is taking some time to load. Try it on version 7. If the issue no longer arises I will close this issue.

**Comment by kokixi** [comment] 2015-12-09 20:34
I've tried this on version 7 and it works perfect now. I think you can already close this issue.

**Comment by designerzim** [comment] 2015-12-09 23:13
Found on version 7: Mac/Firefox

**Comment by designerzim** [comment] 2015-12-09 23:15
Also Safari

**Comment by designerzim** [comment] 2015-12-09 23:15
Probably can't fix it. I think it's a problem with the unity player and browser/OS interaction.

**Comment by kokixi** [comment] 2015-12-12 06:21
fixed on #147

**Closed as completed by kokixi** 2015-12-12 06:21 UTC
