### ISSUE TITLE
First obstacle (Sean's face) doesn't end the game.

### ISSUE THREAD

**Issue by sungry** [sungry/CS177#47] opened 2015-11-28 07:35 UTC
First obstacle doesn't end the game, but from the second one it does. Could someone take a look into this?

**Comment by EricSFChu** [comment] 2015-11-28 17:25
I know what the issue is. Will work on it in time. Whats happening is the face spawn is called before the scripts are initialized.

**Comment by ghost** [comment] 2015-11-30 02:47
I was able to duplicate this "bug" too just by letting the character run as it would on the ground. However, I was also able to kill myself and end the game by jumping towards or landing on the first obstacle. So maybe this bug is really just due to the first obstacle being placed character's short torso, since I think the only way to kill the character is through its torso rather than its entire sprite.

**Comment by kokixi** [comment] 2015-12-03 00:11
This was fixed on #78

**Closed as completed by kokixi** 2015-12-03 00:11 UTC
Labels: bug, duplicate
